[package]
name = "indy-wallet"
version = "0.1.0"
authors = ["Hyperledger Indy Contributors <hyperledger-indy@lists.hyperledger.org>"]
edition = "2018"

[features]
default = []
benchmark = []
mysql = []

[dependencies]
async-trait = "0.1.42"
byteorder = "1.3.2"
futures = { version = "0.3", default-features = false, features = [ "alloc" ] }
indy-api-types = { path = "../indy-api-types"}
indy-utils = { path = "../indy-utils"}
libc = "0.2.114"
log = "0.4.8"
rmp-serde = "0.13.7"
bs58 = "0.4.0"
serde = "1.0.99"
serde_json = "1.0.40"
serde_derive = "1.0.99"
sqlx = { version = "0.6.2", features = [ "sqlite", "mysql", "runtime-tokio-rustls", "json" ] }
zeroize = "~1.5.0"
lru = "0.7.6"

[dev-dependencies]
rand = "0.7.0"
lazy_static = "1.3"
