name: "setup-testing-nodejs-experiment"
description: 'Install library deps, build libvcx'

inputs:
  skip-docker-setup:
    description: 'If true, skip spinning up docker containers'
    required: false
    default: false
  node-version:
    description: 'Version of nodejs'
    required: true

runs:
  using: "composite"
  steps:
    - name: "Print versions after node installation"
      shell: bash
      run: |
        echo "Use Node.js ${{ inputs.node-version }}"
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
    - name: "Print versions after node installation"
      shell: bash
      run: |
        set -x
        npm --version
        node --version
        rustc --version || true;
        cargo --version || true;
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.64.1
    - name: "Print versions after rust toolchain installation"
      shell: bash
      run: |
        set -x
        rustc --version
        cargo --version
