[package]
name = "aries-vcx-agent"
version = "0.1.0"
edition = "2021"

[dependencies]
failure = "0.1.8"
serde = "1.0.145"
aries-vcx = { path = "../../../aries_vcx" }
derive_builder = "0.11.2"
serde_json = "1.0.85"
log = "0.4.17"
actix = "0.13.0"

[dev-dependencies]
uuid = { version = "1.2.1", features = [ "v4" ] }
aries-vcx = { path = "../../../aries_vcx", features = [ "test_utils" ] }
