[package]
name = "aries-vcx-agent"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
failure = "0.1.8"
serde = "1.0.145"
aries-vcx = { path = "../../../aries_vcx" }
messages = { path = "../../../messages" }
derive_builder = "0.11.2"
serde_json = "1.0.85"
log = "0.4.17"
uuid = { version = "1.2.1", features = ["v4"] }

[features]
test_utils = [ "aries-vcx/test_utils" ]
agency_pool_tests = ["test_utils" ]

[dev-dependencies]
tokio = { version = "1.15", features = [ "rt", "macros" ] }
