name: CI-test

on:
  push:
    branches:
      - "**"

env:
  DOCKER_BUILDKIT: 1
  MAIN_BRANCH: main
  URL_DOCKER_REGISTRY: ghcr.io
  DOCKER_IMAGE_AGENCY: ghcr.io/absaoss/vcxagencynode/vcxagency-node:2.2.0
  DOCKER_IMAGE_POOL: pstas/indypool-localhost:1.15.0-localhost

  DOCKER_REPO_LOCAL_ALPINE_CORE: alpine-core
  DOCKER_REPO_LOCAL_LIBVCX: libvcx
  DOCKER_REPO_LOCAL_ANDROID: android-test

  RUST_TOOLCHAIN_VERSON: 1.64.0
  NODE_VERSION: 18

jobs:
  test-node-wrapper:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: "Git checkout"
        uses: actions/checkout@v3
      - name: "Setup NodeJS libvcx testing environment"
        uses: ./.github/actions/setup-testing-nodejs-experiment
        with:
          skip-docker-setup: true
          node-version: ${{ matrix.node-version }}
