name: ci-fast

on:
  push:

jobs:
  rust:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt update -y
          sudo apt-get install -y libsodium-dev libzmq5-dev

      - name: Install Rust toolchain
        run: |
          rustup update --no-self-update stable
          rustup component add rustfmt

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2

      - name: Fetch rust dependencies
        run: |
          cargo fetch

      - name: Buld tests
        run: |
          cargo test --no-run --features general_test
          cargo test --no-run --features "pool_tests agency_tests"
          cargo test --no-run --features "pool_tests agency_v2"

      - name: Run tests
        run: |
          cargo test --locked --features general_test -- --test-threads=1
